version: '3.8'

services:
  postgres-dev:
    image: postgres:16-alpine
    container_name: gurmania-db-dev
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data
    networks:
      - gurmania-dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app-dev:
    build:
      context: ../gurmania
      dockerfile: Dockerfile
    container_name: gurmania-app-dev
    restart: always
    depends_on:
      postgres-dev:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-dev:5432/${POSTGRES_DB}
      NEXTAUTH_URL: https://dev.gurmania.gorstaci.org
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXT_PUBLIC_APP_URL: https://dev.gurmania.gorstaci.org
      # Add other environment variables as needed
      EMAIL_SERVER_HOST: ${EMAIL_SERVER_HOST}
      EMAIL_SERVER_PORT: ${EMAIL_SERVER_PORT}
      EMAIL_SERVER_USER: ${EMAIL_SERVER_USER}
      EMAIL_SERVER_PASSWORD: ${EMAIL_SERVER_PASSWORD}
      EMAIL_FROM: ${EMAIL_FROM}
    ports:
      - "3001:3000"
    networks:
      - gurmania-dev
    command: >
      sh -c "
        npx prisma migrate deploy &&
        npm start
      "

networks:
  gurmania-dev:
    driver: bridge

volumes:
  postgres-dev-data:

